CREATE USER ronaldlopezb WITH PASSWORD 'Sraonndarl8172432';
GRANT CONNECT ON DATABASE postgres TO ronaldlopezb;
GRANT USAGE ON SCHEMA public TO ronaldlopezb;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ronaldlopezb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ronaldlopezb;
